# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d277432f9064091e548307c5367dbc1efb2638be5fe9523e7d659373249c779f407b175302603b1f646c08211224adb54034b541c03abc86e25261ee028c130

test:
  secret_key_base: 2b10289179eb8854132833b128d60395c25f8cbd66b6167463093ff9011c4031a0a528a23db30a54f6b26bdcd8fba94be904e72f6ef500088a34543c78e6b548

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
